### ISSUE TITLE
Questions about the evaluation results

### ISSUE THREAD

**Issue by subversive009** [WHU-USI3DV/CoFiI2P#19]
![image](https://github.com/user-attachments/assets/34cdfbdc-f545-4eab-a11c-6f9e75afb4c1)
![image](https://github.com/user-attachments/assets/17121f0b-48cb-4fac-bc6e-208179bdd793)

Why do the ground truth values of p for each frame in the evaluation results differ, shouldn't the values for each sequence in the annotation file be the same?
Then, could you explain the meaning of each value in the output?
Thank you

**Comment by martin-liao** [comment]
For the KITTI Odometry dataset, we add random distortion while generating the GT pose [link](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/data/kitti.py#L216). 
The bug has been fixed in the Nuscenes dataset [link](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/data/nuscenes.py#L133) by adding a random seed. 
You could use the ``generate_random_transform`` function in the ``nuscenes.py`` file directly, and we will fix the bug in the near future.
Although the distortion is agnostic, the evaluation results should be very close to the results reported in the paper. You can have a try.

**Comment by subversive009** [comment]
Thank you for your reply. I still have some visualization questions. I tried using these randomly generated GT_P to process both point clouds and images for visualization, but some of them failed to display the images properly due to the large random rotation angle.Could you tell me how the visualization is done in your paper or provide the visualization code for KITTI?
![image](https://github.com/user-attachments/assets/1414e3c2-9e7b-40d8-af07-ad99f8b955f9)
Normal display
![image](https://github.com/user-attachments/assets/0f01575e-fcfe-4d1b-8036-a8c49598fd3e)
fail to display

**Comment by martin-liao** [comment]
[link](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/vis_nuscenes_pose.ipynb) for visualization code on the Nuscenes dataset.
We will upload the visualization code for the KITTI Odometry dataset later.

**Comment by martin-liao** [comment]
> Thank you for your reply. I still have some visualization questions. I tried using these randomly generated GT_P to process both point clouds and images for visualization, but some of them failed to display the images properly due to the large random rotation angle.Could you tell me how the visualization is done in your paper or provide the visualization code for KITTI? ![image](https://private-user-images.githubusercontent.com/166592362/381004584-1414e3c2-9e7b-40d8-af07-ad99f8b955f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTMxNzUsIm5iZiI6MTczMDE5Mjg3NSwicGF0aCI6Ii8xNjY1OTIzNjIvMzgxMDA0NTg0LTE0MTRlM2MyLTllN2ItNDBkOC1hZjA3LWFkOTlmOGI5NTVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwOTA3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTdkYmZhNzQ3Mzc2ZmNlMjFkNTI3NzU0NTI2ZWQ4NWRkNjM4YmY5NDFjMmRiMzRhNmQxOTE2ZmI2YWVkN2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z5IltPbDYpt4W-lOiRsom7Lpme7sl-FLhPyo_25Rr9c) Normal display ![image](https://private-user-images.githubusercontent.com/166592362/381004797-0f01575e-fcfe-4d1b-8036-a8c49598fd3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTMxNzUsIm5iZiI6MTczMDE5Mjg3NSwicGF0aCI6Ii8xNjY1OTIzNjIvMzgxMDA0Nzk3LTBmMDE1NzVlLWZjZmUtNGQxYi04MDM2LWE4YzQ5NTk4ZmQzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwOTA3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWM5YzczOTVkZTE4ZmM3YzRjNzNkMWRjYmFhNTBlZjcwNjM5NzlmYzM3ZDQxZDhlMjBjZWM5NTI3NzVlMmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iitgiZ31UVYiAD1OtMqCmx5Oi1qTNmtX8k-roPkwRlM) fail to display

It seems the image was rotated and scaled, which should not happen: any distortion in the extrinsic parameters should not affect the intrinsic parameters of the camera.

**Comment by subversive009** [comment]
Hello, I noticed that the final output P_pred is actually the inverse matrix of the random generated GT_P.  Does this mean that this model actually recovers the point cloud that have been transformed to a random coordinate system to the camera coordinate system. Is the use of randomly generated external parameters as GT_P because the variation between external parameters in the dataset is too small？  If I want to achieve inputting a picture and a point cloud and obtaining extrinsic parameters that are similar to those in the labeled file, will I not be able to achieve this because the data set is not rich enough?
